server:
  port: 8080

# Datasource configurations
spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/currencyDb?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

hibernate:
  hbm2ddl:
    auto: create

# Path of the OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  # Path of the Swagger UI
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

api:
  title: Exchange Rates API
  description: Api to retrieve exchange rates data from different rate providers

#Providers configuration
providers:
  monobank:
    api: https://api.monobank.ua/bank/currency
  privatbank:
    api: https://api.privatbank.ua/p24api/pubinfo?exchange&coursid=5
  minfin:
    api: https://api.minfin.com.ua/mb/8f42f58043de5bcb4b12aa30a3b0e71a2af6581b

exchange:
  baseLiteral: UAH
  baseCode: 980
  targetLiteral:
    - usd
    - eur
  targetCode:
    - 840
    - 978
